- hosts: all
  vars: 
    ansible_connection: network_cli
    gather_facts: no
    ansible_network_cli_ssh_type: paramiko
    ansible_network_os: ios
    ansible_port: 22
  tasks:
    - name: Perform the actual configuration change
      ios_config:
        lines:
          - "10 permit ip host 10.0.0.1 any log"
          - "20 permit ip host 192.0.2.1 any log"
          - "30 permit ip host 192.0.2.2 any log"
          - "40 permit ip host 192.0.2.3 any log"
          - "50 permit ip host 192.0.2.4 any log"
          - "60 permit ip host 192.0.2.5 any log"
        parents: "ip access-list extended test"
        before: "no ip access-list extended test"
        match: strict
        replace: block
