- hosts: all
  vars: 
    ansible_connection: network_cli
    gather_facts: no
    ansible_network_cli_ssh_type: paramiko
    ansible_network_os: ios
    ansible_port: 22
  tasks:
    - name: Audit test ACL
      ios_config:
        lines:
          - permit ip host 192.0.2.1 any log
          - permit ip host 192.0.2.2 any log
          - permit ip host 192.0.2.3 any log
          - permit ip host 192.0.2.4 any log
          - permit ip host 192.0.2.5 any log
        parents: ip access-list extended test
        before: no ip access-list extended test
        match: exact
        replace: block
      notify: "Save config"
  
  handlers:
   - name: Save config
     ios_command:
       commands: "write mem"
       timeout: 40
     when: not ansible_check_mode
