- name: Add ACL to Switch
  hosts: SW1
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    gather_facts: no
    ansible_network_cli_ssh_type: paramiko
    ansible_port: 22
    ansible_command_timeout: 60

    ip_networks:
      - 192.168.1.0/24
      - 10.0.0.0/16
      - 10.0.0.0/18
      
  tasks:
    - name: Calculate network and netmask
      set_fact:
        net_masks: "{{ net_masks | default([]) + [(item | ipaddr('network')) + ' ' + (item | ipaddr('netmask'))] }}"
      loop: "{{ ip_networks }}"
      loop_control:
        label: "{{ item }}"

    - name: Display Netmask Masks
      debug:
        var: net_masks
    
    - name: Calculate netmask from CIDR notations
      gather_facts: no
      set_fact:
        wildcard_masks: "{{ wildcard_masks | default([]) + [item | ansible.utils.ipaddr('hostmask')] }}"
      loop: "{{ ip_networks }}"

    - name: Display Wildcard Masks
      debug:
        var: wildcard_masks

    # - name: Remove ACL 25 from VTY lines 0 15
    #   cisco.ios.ios_config:
    #     parents:
    #       - line vty 0 15
    #     lines:
    #       - no access-class 25 in

    # - name: Audit ACL 25 - Edit if differences detected
    #   cisco.ios.ios_config:
    #     lines:
    #       - permit host 192.0.2.1
    #       - permit host 192.0.2.2
    #       - permit host 192.0.2.3
    #       - permit host 192.0.2.4
    #       - permit host 192.0.2.5
    #       - permit host 10.0.0.20
    #       - permit host 10.0.0.16
    #     parents: ip access-list standard 25
    #     before: no ip access-list standard 25
    #     match: exact
    #     replace: block
    #   notify: "Save config via ios_config module"
    
    # - name: Audit SSH Access ACL - Edit if differences detected
    #   cisco.ios.ios_config:
    #     lines:
    #       - permit ip host 10.0.0.16 any
    #       - permit ip host 10.0.0.20 any
    #       - permit ip host 10.0.0.1 any
    #       - deny   ip any any
    #     parents: ip access-list standard SSH_access
    #     before: no ip access-list standard SSH_access
    #     match: exact
    #     replace: block
    #   notify: "Save config via ios_config module"

    # - name: Add ACL 25 to VTY lines 0 15
    #   cisco.ios.ios_config:
    #     parents:
    #       - line vty 0 15
    #     lines:
    #       - access-class 25 in

 

  handlers:
   - name: Save config
     ios_command:
       commands: "write mem"
       #timeout: 40
     when: not ansible_check_mode
     
   - name: Save config via ios_config module
     ios_config:
       save_when: always
     when: not ansible_check_mode
