- name: Add ACL to Switch
  hosts: SW1
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    gather_facts: no
    ansible_network_cli_ssh_type: paramiko
    ansible_port: 22
    ansible_command_timeout: 60

    ip_networks:
      - 192.168.1.0/24
      - 10.0.0.0/16
      - 192.168.1.1/18
      - 10.184.192.253/26
      
  tasks:
    # - name: Calculate network and netmask
    #   set_fact:
    #     net_masks: "{{ net_masks | default([]) + [(item | ansible.utils.ipaddr('network')) + ' ' + (item | ansible.utils.ipaddr('netmask'))] }}"
    #   loop: "{{ ip_networks }}"
    #   loop_control:
    #     label: "{{ item }}"

    # - name: Display Netmask Masks
    #   debug:
    #     var: net_masks
    
    # - name: Calculate network and wildcard
    #   set_fact:
    #     wildcard_masks: "{{ wildcard_masks | default([]) + [(item | ansible.utils.ipaddr('network')) + ' ' + (item | ansible.utils.ipaddr('hostmask'))] }}"
    #   loop: "{{ ip_networks }}"
    #   loop_control:
    #     label: "{{ item }}"

    # - name: Display Wildcard Masks
    #   debug:
    #     var: wildcard_masks
    


    # - name: Remove ACL 25 from VTY lines 0 15
    #   cisco.ios.ios_config:
    #     parents:
    #       - line vty 0 15
    #     lines:
    #       - no access-class 25 in
    
    - name: Audit SSH Access ACL - Edit if differences dete
      cisco.ios.ios_config:
        lines:
          - 
        parents: ip access-list standard SSH_access
        before: no ip access-list standard SSH_access
        
        match: exact
        replace: block
      notify: "Save config via ios_config module"

    # - name: Add ACL to VTY lines 0 15
    #   cisco.ios.ios_config:
    #     parents:
    #       - line vty 0 15
    #     lines:
    #       - access-class SSH_access in

 

  handlers:
   - name: Save config
     ios_command:
       commands: "write mem"
       #timeout: 40
     when: not ansible_check_mode
     
   - name: Save config via ios_config module
     ios_config:
       save_when: always
     when: not ansible_check_mode
