- hosts: all
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_port: 22
    #ansible_network_cli_ssh_type: paramiko
    #ansible_ssh_common_args: "-o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-dss -o KexAlgorithms=+diffie-hellman-group1-sha1 -c aes128-cbc"
    #ANSIBLE_HOST_KEY_CHECKING: "False"
    #ansible_user: "ansible"
    #ansible_ssh_pass: "password"
  tasks:
    - name: Gather listed acls with provided configurations
      cisco.ios.ios_acls:
        config:
        state: gathered
