- hosts: all
  gather_facts: no

  vars:
    ansible_connection: network_cli
    gather_facts: no
    ansible_network_cli_ssh_type: paramiko
    ansible_network_os: ios
    ansible_port: 22

    ntp_servers:
      - ntp server 10.0.0.2
      
  tasks:
  - name: Gather Facts (ios)
    cisco.ios.ios_facts: 
    when: ansible_network_os == 'ios'
  
  - name: Display Device model
    debug:
      msg: " {{ ansible_net_model }} "

  - name: Perform actions only if model matches when evaluation
    block:
      - name: get the current ntp server configs
        ios_command:
          commands:
            - "show running-config full | include ntp server"
        register: get_config

      - debug: var=get_config.stdout_lines

      - name: set ntp server commands
        with_items: "{{ ntp_servers }}"
        ios_config:
          lines:
              - "{{ item }}"
        register: set_ntp

      - name: remove ntp server commands
        when: "(get_config.stdout_lines[0] != '') and (item not in ntp_servers)"
        with_items: "{{ get_config.stdout_lines[0] }}"
        register: remove_ntp
        ios_config:
          lines:
            - "no {{ item }}"
            

    when: ansible_net_model | regex_search('2\d{3}')
