- hosts: all
  gather_facts: no

  vars:
    ansible_connection: network_cli
    gather_facts: no
    ansible_network_cli_ssh_type: paramiko
    ansible_network_os: ios
    ansible_port: 22

    OG_names:
      - object-group network ADFS
      
  tasks:
  - name: Get model number and match to regex
    cisco.ios.ios_facts: 
    when: ansible_network_os == 'ios'

  - name: Perform tasks if model is 9K series
    block:
      - name: Get the current object-group configs
        ios_command:
          commands:
            - "show running-config full | include object-group network"
        register: get_config

      - debug: var=get_config.stdout_lines

      - name: set ADFS object-group
        ios_config:
          lines:
              - host 10.0.0.1
          parents: object-group network ADFS
          before: no object-group network ADFS
          match: exact
          replace: block
        register: set_og

      - name: remove object-group server commands
        when: "(get_config.stdout_lines[0] != '') and (item not in OG_names)"
        with_items: "{{ get_config.stdout_lines[0] }}"
        register: remove_og
        ios_config:
          lines:
            - "no {{ item }}"
            
    when: ansible_net_model | regex_search('2\d{3}')
