- name: Cisco show version example
  hosts: cisco_L3_9k_devices
  connection: paramiko
  gather_facts: false

  vars: # for execution environment

    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    #ansible_ssh_common_args: "-oKexAlgorithms=+diffie-hellman-group14-sha1 -oCiphers=+aes128-cbc"
    #ANSIBLE_HOST_KEY_CHECKING: "False"
    ansible_network_cli_ssh_type: paramiko
    ansible_become: yes
    ansible_become_method: enable

  tasks:

  - name: Gather only the config and default facts
    cisco.ios.ios_facts:
      gather_subset:
      - config

  - name: Show facts
    debug:
      msg: "{{ ansible_facts.net_version }}"
