- hosts: all
  vars: 
    ansible_connection: network_cli
    gather_facts: no
    ansible_network_cli_ssh_type: paramiko
    ansible_network_os: ios
    ansible_port: 22
  tasks:
    - name: Audit TACACs Settings
      ios_config:
        lines:
          - tacacs-server host 10.0.0.4
          - tacacs-server host 10.0.0.5
        # parents: ip access-list extended test
        # before: 
        #   - no tacacs-server host 10.0.0.4
        match: line
        replace: block
      notify: "Save config via ios_config module"
  
  handlers:
   - name: Save config
     ios_command:
       commands: "write mem"
       #timeout: 40
     when: not ansible_check_mode
     
   - name: Save config via ios_config module
     ios_config:
       save_when: always
     when: not ansible_check_mode
